/**
 * Project service definitions for Docker-backed CI.
 *
 * Fixed local endpoints (agreed across compose file, workflow step, skill
 * and prompts) so no per-project wiring is needed. Credentials are
 * ephemeral CI-only defaults — NEVER use them outside throwaway runners.
 */
export const SERVICE_DEFS: Record<
  string,
  { image: string; env: Record<string, string>; check: string }
> = {
  postgres: {
    image: "postgres:16-alpine",
    env: {
      DATABASE_URL: "postgres://postgres:postgres@localhost:5432/app",
    },
    check: "pg_isready -h localhost -p 5432 -U postgres",
  },
  redis: {
    image: "redis:7-alpine",
    env: {
      REDIS_URL: "redis://localhost:6379",
    },
    check: "redis-cli -h localhost -p 6379 ping",
  },
  mongo: {
    image: "mongo:7",
    env: {
      MONGO_URL: "mongodb://localhost:27017/app",
    },
    check: "mongosh --quiet --eval 'db.runCommand({ping:1})' mongodb://localhost:27017/app",
  },
  minio: {
    image: "minio/minio:latest",
    env: {
      S3_ENDPOINT: "http://localhost:9000",
      S3_ACCESS_KEY: "minioadmin",
      S3_SECRET_KEY: "minioadmin",
      S3_BUCKET: "uploads",
      S3_REGION: "us-east-1",
    },
    // MinIO speaks the S3 API: code written against it also runs on R2/AWS.
    check: "curl -sf http://localhost:9000/minio/health/live",
  },
};

export const KNOWN_SERVICES = Object.keys(SERVICE_DEFS);

/**
 * Deterministic compose file from a service list (pure — unit-testable).
 * Data is ephemeral (tmpfs/anonymous volumes): perfect for tests, useless
 * for persistence. Agents must seed fixtures per run.
 */
export function renderComposeYaml(services: string[]): string {
  const picked = services.filter((s) => SERVICE_DEFS[s]);
  const blocks: string[] = [];
  if (picked.includes("postgres")) {
    blocks.push(`  postgres:
    image: ${SERVICE_DEFS.postgres.image}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 20`);
  }
  if (picked.includes("redis")) {
    blocks.push(`  redis:
    image: ${SERVICE_DEFS.redis.image}
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 20`);
  }
  if (picked.includes("mongo")) {
    blocks.push(`  mongo:
    image: ${SERVICE_DEFS.mongo.image}
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ping:1})"]
      interval: 5s
      timeout: 5s
      retries: 20`);
  }
  if (picked.includes("minio")) {
    blocks.push(`  minio:
    image: ${SERVICE_DEFS.minio.image}
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"`);
  }
  return `# Auto-generated by OpenCode Orchestrator — ephemeral CI services.\n# Do NOT use these credentials outside throwaway runners.\nservices:\n${blocks.join("\n")}\n`;
}

/** Flat env map for the picked services (exported via $GITHUB_ENV). */
export function serviceEnv(services: string[]): Record<string, string> {
  const out: Record<string, string> = {};
  for (const s of services) {
    if (SERVICE_DEFS[s]) Object.assign(out, SERVICE_DEFS[s].env);
  }
  return out;
}
