import { existsSync, mkdirSync } from "fs";
import { dirname } from "path";
import { CONFIG } from "./config.ts";
import type { Roadmap, TaskItem, TaskStatus } from "./types.ts";

export class StateManager {
  /**
   * Load roadmap from state file. Returns null if not initialized yet.
   */
  public static async loadRoadmap(): Promise<Roadmap | null> {
    if (!existsSync(CONFIG.ROADMAP_FILE)) {
      return null;
    }
    try {
      const content = await Bun.file(CONFIG.ROADMAP_FILE).text();
      return JSON.parse(content) as Roadmap;
    } catch (err) {
      console.error(`Failed to parse roadmap file at ${CONFIG.ROADMAP_FILE}:`, err);
      return null;
    }
  }

  /**
   * Save roadmap to JSON and auto-generate state/PROGRESS.md
   */
  public static async saveRoadmap(roadmap: Roadmap): Promise<void> {
    const dir = dirname(CONFIG.ROADMAP_FILE);
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
    }

    roadmap.updatedAt = new Date().toISOString();
    await Bun.write(CONFIG.ROADMAP_FILE, JSON.stringify(roadmap, null, 2));
    await this.updateProgressMarkdown(roadmap);
  }

  /**
   * Find tasks whose dependencies are fully COMPLETED and currently PENDING
   */
  public static getReadyTasks(roadmap: Roadmap, maxCount: number): TaskItem[] {
    const completedTaskIds = new Set(roadmap.tasks.filter((t) => t.status === "COMPLETED").map((t) => t.id));

    const inProgressCount = roadmap.tasks.filter((t) => t.status === "IN_PROGRESS" || t.status === "IN_REVIEW").length;

    const availableSlots = Math.max(0, maxCount - inProgressCount);
    if (availableSlots <= 0) {
      return [];
    }

    const ready: TaskItem[] = [];
    for (const task of roadmap.tasks) {
      if (task.status !== "PENDING") continue;

      const allDepsMet = task.dependencies.every((depId) => completedTaskIds.has(depId));
      if (allDepsMet) {
        ready.push(task);
        if (ready.length >= availableSlots) break;
      }
    }

    return ready;
  }

  /**
   * Generate human & AI readable master progress report in Markdown.
   * Redacted mode (dual-repo public dashboard) drops titles, notes and
   * branches — IDs, roles, statuses and dependencies only.
   */
  public static renderProgressMarkdown(roadmap: Roadmap, opts?: { redact?: boolean }): string {
    const redact = !!opts?.redact;
    const total = roadmap.tasks.length;
    const completed = roadmap.tasks.filter((t) => t.status === "COMPLETED").length;
    const inProgress = roadmap.tasks.filter((t) => t.status === "IN_PROGRESS").length;
    const inReview = roadmap.tasks.filter((t) => t.status === "IN_REVIEW").length;
    const pending = roadmap.tasks.filter((t) => t.status === "PENDING").length;
    const failed = roadmap.tasks.filter((t) => t.status === "FAILED").length;

    const pct = total === 0 ? 0 : Math.round((completed / total) * 100);

    const statusBadge = (s: TaskStatus) => {
      switch (s) {
        case "COMPLETED":
          return "✅ COMPLETED";
        case "IN_PROGRESS":
          return "⚡ IN_PROGRESS";
        case "IN_REVIEW":
          return "🔍 IN_REVIEW";
        case "PENDING":
          return "⏳ PENDING";
        case "FAILED":
          return "❌ FAILED";
      }
    };

    let md = `# 🚀 Project Progress: ${roadmap.projectName}\n\n`;
    md += `> **Status:** \`${roadmap.globalStatus}\` | **Updated:** ${new Date(roadmap.updatedAt).toLocaleString()}\n\n`;
    md += `### 📊 Milestone Overview\n`;
    md += `- **Progress:** ${completed} / ${total} tasks (${pct}%)\n`;
    md += `- **Active:** ${inProgress} in progress, ${inReview} in review\n`;
    md += `- **Queue:** ${pending} pending, ${failed} failed\n\n`;

    md += `### 📋 Task Breakdown\n\n`;
    if (redact) {
      md += `| ID | Role | Status | Dependencies |\n`;
      md += `| :--- | :--- | :--- | :--- |\n`;
    } else {
      md += `| ID | Title | Role | Status | Branch | Dependencies | Notes |\n`;
      md += `| :--- | :--- | :--- | :--- | :--- | :--- | :--- |\n`;
    }

    for (const task of roadmap.tasks) {
      if (redact) {
        const deps = task.dependencies.length > 0 ? task.dependencies.map((d) => `\`${d}\``).join(", ") : "-";
        md += `| \`${task.id}\` | \`${task.role}\` | ${statusBadge(task.status)} | ${deps} |\n`;
        continue;
      }
      const deps = task.dependencies.length > 0 ? task.dependencies.join(", ") : "-";
      const notes = task.reviewNotes ? task.reviewNotes.replace(/[\r\n]+/g, " ") : "-";
      md += `| \`${task.id}\` | **${task.title}** | \`${task.role}\` | ${statusBadge(task.status)} | \`${task.branch}\` | ${deps} | ${notes} |\n`;
    }

    md += `\n---\n*Auto-generated by OpenCode Orchestrator Engine*\n`;
    return md;
  }

  public static async updateProgressMarkdown(roadmap: Roadmap): Promise<void> {
    const md = this.renderProgressMarkdown(roadmap);
    await Bun.write(CONFIG.PROGRESS_MD_FILE, md);
  }

  /**
   * Field-wise merge of two roadmaps (concurrent-tick conflict resolution).
   * Terminal states (COMPLETED/FAILED) always win — a stale copy must never
   * resurrect finished tasks. All other tasks go to the newer updatedAt.
   * Top-level metadata follows remote, except missing project linkage which
   * is backfilled from local.
   */
  public static mergeRoadmaps(local: Roadmap, remote: Roadmap): Roadmap {
    const merged = new Map<string, TaskItem>();
    for (const rt of remote.tasks) merged.set(rt.id, { ...rt });
    for (const lt of local.tasks) {
      const rt = merged.get(lt.id);
      if (!rt) {
        merged.set(lt.id, { ...lt });
        continue;
      }
      const terminal = (s: string) => s === "COMPLETED" || s === "FAILED";
      if (terminal(rt.status) || terminal(lt.status)) {
        const ltTime = Date.parse(lt.updatedAt || "") || 0;
        const rtTime = Date.parse(rt.updatedAt || "") || 0;
        const newer = ltTime >= rtTime ? lt : rt;
        // Resurrection wins: a NEWER non-terminal state (/retry, watchdog or
        // auto-resurrect) overrides an older terminal one. Stale copies still
        // lose — an OLDER non-terminal never beats a newer terminal.
        if (!terminal(newer.status)) {
          merged.set(lt.id, { ...newer });
          continue;
        }
        merged.set(lt.id, {
          ...(terminal(lt.status) ? lt : rt),
          reviewNotes: newer.reviewNotes,
          attempts: Math.max(lt.attempts, rt.attempts),
          resurrections: Math.max(lt.resurrections || 0, rt.resurrections || 0),
          failedAt: newer.failedAt ?? (terminal(lt.status) ? lt : rt).failedAt,
          updatedAt: newer.updatedAt,
        });
        continue;
      }
      const ltTime2 = Date.parse(lt.updatedAt || "") || 0;
      const rtTime2 = Date.parse(rt.updatedAt || "") || 0;
      const newerFirst = ltTime2 >= rtTime2;
      merged.set(lt.id, { ...(newerFirst ? lt : rt) });
    }
    const ordered = [
      ...remote.tasks.map((t) => merged.get(t.id)!),
      ...[...merged.values()].filter((t) => !remote.tasks.some((r) => r.id === t.id)),
    ];
    return {
      ...remote,
      projectNumber: remote.projectNumber ?? local.projectNumber,
      projectUrl: remote.projectUrl ?? local.projectUrl,
      services: remote.services ?? local.services,
      tasks: ordered,
      updatedAt: new Date().toISOString(),
    };
  }
}
